### ISSUE TITLE
Neoweather should be using #require

### ISSUE THREAD

**Issue by cat-haines** [electricimp/WS2812#3]
The Neoweather example should have the Neopixel class pulled out and replaced with:

``` squirrel
#require "Neopixels.class.nut:1.0.1"
```

**Comment by ersatzavian** [comment]
filed a pivotal. can you do that instead next time? It's sheer luck I found this.

**Comment by cat-haines** [comment]
Resolved in 5e0534672591016992a59b8b8a4cdbea20304a2d.
