### ISSUE TITLE
Put try/catch around assert statements in set() and fill()

### ISSUE THREAD

**Issue by kwitgit** [electricimp/WS2812#8]
Would it be possible (and is it a good idea) to publish a version 2.0.2 with assert statements caught in the set() and fill() methods? Currently when LEDs are caught in a situation in which they are not lit (not quite sure what makes that happen), the first assert statement in set() causes a "ERROR: assertion failed" from the device and it then errors out in a loop and cannot get back to a working state.

I suggest something like the following.  Replace all lines similar to this:
`assert(color[0] >= 0 && color[0] <= 255);`

with something resembling this (apologies for any noob-ishness exhibited):

```
try {
    assert(color[0] >= 0 && color[0] <= 255);
} catch(color0error) {
    // Recover by setting color to white
    server.error("Tried to change color[0] to " + color[0] + " but valid values are 0 to 255.")
    set color[0] = 255;
}

```

**Comment by betzrhodes** [comment]
New version released v2.0.2 -
Asserts replaced with conditionals that adjust out of range values to closest in range values.
